### ISSUE TITLE
Standard pipelines

### ISSUE THREAD

**Issue by cherylepatrick** [SuperNEMO-DBD/Falaise#133] opened 2019-03-18 17:02 UTC
Not sure if this is an actual Falaise/brew issue or if it is just an issue of docs, but I would like to sort it by next week. I have the new Falaise install on my laptop. http://supernemo.org/Falaise/usingflreconstruct.html claims that I can get to the standard pipeline list by running `flreconstruct --help-pipeline-list` but I think this is not the most up to date list of pipelines and also... the pipeline it returned did not work for me
```
dev192-150-181-151:test cpatrick$ flreconstruct --help-pipeline-list
List of supported reconstruction pipeline:
urn:snemo:demonstrator:reconstruction:1.0.0:pipeline : Processing pipeline modules for the SuperNEMO reconstruction setup (tag 1.0.0)
urn:snemo:demonstrator:reconstruction:hc-1.0.0:pipeline : Processing pipeline modules for the SuperNEMO reconstruction setup (Half-Commissioning tag 1.0.0)
dev192-150-181-151:test cpatrick$ flreconstruct -i sim0nubb_1k.brio -p urn:snemo:demonstrator:reconstruction:1.0.0:pipeline -o rec0nubb_1k.brio
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for /tmp/bayeux-20190305-83906-14gp9nv/Bayeux-3.3.0/bayeux.build/source/inc/brio/detail/brio_record.h
   requested to autoload type TArrayCMod
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for /tmp/bayeux-20190305-83906-14gp9nv/Bayeux-3.3.0/bayeux.build/source/inc/brio/detail/brio_record.h
   requested to autoload type brio_record
[fatal:falaise::exit_code FLReconstruct::do_pipeline(const FLReconstruct::FLReconstructParams &):156] Failed to initialize pipeline : [void dpp::module_manager::_create_module(dpp::module_entry_type &):279: Cannot find module factory with ID 'snemo::reconstruction::cat_tracker_clustering_module' for module named 'CATTrackerClusterizer' !]
```

**Comment by drbenmorgan** [comment] 2019-03-19 15:10
Hi @cherylepatrick, I've transferred this to Falaise as I think it's a bug across the `--help-pipeline-list` plus the URNs/Scripts. An outline of the issue/possible solutions are below, apologies for the length as I wanted to get things clear in my mind! @macolino and @yramachers should also take a look as it'll impact scripting of calibration/reconstruction workflows going forward

- The `urn:snemo:demonstrator:reconstruction:1.0.0:pipeline` given by `--help-pipeline-list` is misleading. It's *not* a pointer (I'll use the term "pointer" in place of "URN" as that's clearer description of what URNs do)  to a script that `flreconstruct` can run, rather, it points to a file only defining modules. That's the cause of the error you see, as it doesn't create any of the other infrastructure needed such as loading plugins
  - Now, the Pointer/what it points to is defined here: https://github.com/SuperNEMO-DBD/Falaise/blob/bec42c8e6f5bae1cb028030f32d9c45d29285789/resources/urn/resolvers/snemo_reconstruction_resolver.conf#L4-L12
  - The important bit there is that `urn:snemo:demonstrator:reconstruction:1.0.0` points to this file which is a script that `flreconstruct` can run: https://github.com/SuperNEMO-DBD/Falaise/blob/bec42c8e6f5bae1cb028030f32d9c45d29285789/resources/snemo/demonstrator/reconstruction/pipeline/flreconstruct.conf#L16-L26
  - Here, it loads the needed plugins, and then sets up the actual processing pipeline in the last lines, which basically say "use the pipeline configuration that's pointed to by `urn:snemo:demonstrator:reconstruction:1.0.0`". If you recall back earlier, *that* points to this file: https://github.com/SuperNEMO-DBD/Falaise/blob/bec42c8e6f5bae1cb028030f32d9c45d29285789/resources/snemo/demonstrator/reconstruction/pipeline/modules.defs#L1-L75
- There are also the actual scripts: https://github.com/SuperNEMO-DBD/Falaise/blob/bec42c8e6f5bae1cb028030f32d9c45d29285789/resources/snemo/demonstrator/reconstruction/official-1.0.0.conf#L1-L90 and https://github.com/SuperNEMO-DBD/Falaise/blob/bec42c8e6f5bae1cb028030f32d9c45d29285789/resources/snemo/demonstrator/reconstruction/official-2.0.0.conf#L1-L103 neither of which are pointed to by any URN
- These can be run (tested in the `supernemo/falaise:develop` container) by passing `-p "@falaise:snemo/demonstrator/reconstruction/official-1.0.0.conf"` (or replace `1.0.0` with `2.0.0`)
- From what I can see, `official-1.0.0.conf` has different settings for the modules from `modules.defs`,  obviously `official-2.0.0.conf` is the current recommended.

Clearly, we need to make some longer term decisions here on managing official pipelines given the tangle apparent in the above (see also #118 which is critical for getting mag field etc settings right).

For the upcoming workshop, where we'll work with the "develop" version, I would propose the following:

1) Show only use of the "@falaise:..." path form to run `flreconstruct` with builtin pipelines.
2) Rename (via a PR to develop) `official-1.0.0.conf`, `official-2.0.0.conf` to, say, `old.pipeline.conf` `production.pipeline.conf`or similar.
3) For "falaise 4" which'll be out after next week, update the docs with this

What do you think? It's not ideal, but should allow straightforward running. It's going to be fairly heavily connected with #122 and how to properly manage resources/scripts via Git tagging, stored "provenance" in ROOT, or similar going forward.

**Comment by cherylepatrick** [comment] 2019-03-19 16:43
Oh interesting! So it's actually kind of split in half at the moment. I'm on board with your proposal, with one possible suggestion - should we keep the `official-1.0.0.conf` etc names, but then make a `production.pipeline.conf` which is symlinked to whatever the current approved version is (2.0.0 at the moment)? Might be easier going forward?

**Comment by drbenmorgan** [comment] 2019-03-19 16:53
Yep, that's a better idea for naming, so will prepare the PR on that basis. Worst case if a symlink doesn't work, I'll just direct copy.

**Closed** 2019-05-07 12:42 UTC
