### ISSUE TITLE
Flsimulate issue for PMT Glass vertexes

### ISSUE THREAD

**Issue by lemiere** [SuperNEMO-DBD/Falaise#120] opened 2018-11-05 16:25 UTC
Hi,

I tried to simulate a huge amount of K40 in the PMT Glass bulk (10^12 events)
With Simulation version   :
        * Falaise : 3.3.0
        * Bayeux  : 3.3.0
        * Boost   : 106300
        * Geant4  : 9.6.4

With URN: urn:snemo:demonstrator:simulation:2.3

With variant.profile : 
[registry="vertexes"]
generator = "pmt_main_wall_glass_bulk"

[registry="primary_events"]
generator = "K40"

------
> -------- WWWW ------- G4Exception-START -------- WWWW -------
> *** G4Exception : GeomNav1002
>       issued by : G4Navigator::ComputeStep()
> Track stuck or not moving.
>           Track stuck, not moving for 10 steps
>           in volume -calo.PMT_HAMAMATSU_R5912.model.log_PV- at point (782.813,-1683.75,258.657)
>           direction: (0.414766,0.63379,0.652901).
>           Potential geometry or navigation problem !
>           Trying pushing it of 1e-07 mm ...Potential overlap in geometry!
> 
> *** This is just a warning message. ***

But I never successfully produced a file.
terminate called after throwing an instance of 'std::logic_error'
  what():  [static geomtools::vector_3d genvtx::right_circular_conical_frustrum::random_volume(mygsl::rng&, double, double, double, double, double, double, double, double):151: Cannot compute e !]
/var/spool/sge/ccwsge0580/job_scripts/54048682: line 25: 154808 Aborted

**Comment by drbenmorgan** [comment] 2018-11-06 09:10
Could you post the minimum `flsimulate` script needed to reproduce the issue please? 

Does the terminate happen randomly, always, or after a fixed number of events? The error appears to be in genvtx rather than Geant4, though it's not clear if they are related.

**Comment by drbenmorgan** [comment] 2019-08-05 15:34
Closing due to lack of requested feedback.

**Closed by drbenmorgan** 2019-08-05 15:34 UTC
Labels: bug
