### ISSUE TITLE
Falaise install. issue using ninja

### ISSUE THREAD

**Issue by lemiere** [SuperNEMO-DBD/Falaise#19] opened 2017-05-31 19:18 UTC
Dear all,

I tried to install Falaise-3.0.0 on my laptop (ubuntu 16.04)
Cadfael -- OK
Bayeux -- OK
Falaise --->
I did : 
 cmake \
 -DCMAKE_BUILD_TYPE:STRING=Release \
 -DCMAKE_INSTALL_PREFIX:PATH="${FL_DEV_INSTALL_DIR}" \
 -DCMAKE_PREFIX_PATH=$CADFAEL_PATH \
 -DCMAKE_FIND_ROOT_PATH:PATH="$(bxquery --prefix);$CADFAEL_PATH" \
 -DFALAISE_COMPILER_ERROR_ON_WARNING=ON \
 -DFALAISE_WITH_DEVELOPER_TOOLS=ON \
 -DFALAISE_ENABLE_TESTING=ON \
 -DFALAISE_WITH_DOCS=ON \
 -DFALAISE_WITH_COMPANIONS=ON \
 -GNinja \
 ${FL_DEV_SOURCE_DIR}
next : 
ninja 
next : 
ninja test
ninja: error: unknown target 'test', did you mean 'help'?
ninja install
ninja: error: unknown target 'install'

I did ninja help --> there's nothing about install or test...
somebody knows ? 

Yv

**Comment by drbenmorgan** [comment] 2017-06-01 09:55
Hi @lemiere, I've tried this locally on Mac and I cannot reproduce - could you check and post the output of:

```
$ which cmake
$ which ninja
$ cmake --version
$ ninja --version
```

please?

**Comment by drbenmorgan** [comment] 2018-03-23 16:24
Closing this as outdated, and that `ninja` builds have been running through CI for a while now without issue. Please reopen if required.

**Closed by drbenmorgan** 2018-03-23 16:24 UTC
