### ISSUE TITLE
Bi207 source vertex generator - weighted activities

### ISSUE THREAD

**Issue by cherylepatrick** [SuperNEMO-DBD/Falaise#237] opened 2021-06-03 14:13 UTC
Can we improve the vertex generator for the Bi207 calibration sources by weighting the number of events from each source by its measured activity? Starting this as a placeholder - if anyone finds the documentation of which source is where, and the activities of the individual sources, link them here!

**Comment by cherylepatrick** [comment] 2021-06-03 14:30
https://tel.archives-ouvertes.fr/tel-02122290/document I think the relative activities are in tables A5-A8 of @miroslav-macko 's thesis, page 197.
Looks like Fred planned to do measurements at Bordeaux http://nile.hep.utexas.edu/cgi-bin/DocDB/ut-nemo/private/ShowDocument?docid=4668 but I'm not sure if these supersede the ones in Miro's doc (they might be the results in table A11-12).
I've mailed Karol and Ramon to ask if they can point us at which source is where.

**Comment by miroslav-macko** [comment] 2021-06-03 20:23
Hello,

I have the values of activities with high precision (sub percent precision for at least half of them if I remember). During June (according to the availability of both of us) we discussed that we would upload the final report to the DocDB with the values and other details with Fred. My thesis gives some level of information but the study was finished afterwards so the latest news are in the report which we will just put online. Later we would also like to publish it as an article. We did very precise uncertainty estimation.

**Comment by cherylepatrick** [comment] 2021-06-03 20:37
Perfect, thanks @miroslav-macko !

**Comment by miroslav-macko** [comment] 2021-08-09 15:21
I apologize a lot but I have uploaded the report only today. It is on DocDB, document number 5480. This report was an attempt to give a detailed explanation of the measurements so it contained lot of uninteresting details for someone who only needs numbers. The numbers (activities + their relative uncertainties) can be found in the last two columns of Tables 4 and 5. Some sources were measured twice. In such case, I recommend to take the value with smaller uncertainty ("absolute" measurement). Graphical representation of all the activities is in the Figure 10. The positions of the sources in the demonstrator are to be found in my thesis (DocDB 4816) on page 77, Table 3.7.  The report was written after the thesis so the report is more relevant. Let me know if there are some questions.

**Comment by lemiere** [comment] 2021-09-07 11:49
Here a csv file obtained thnaks to Miroslav documents.
This file will be used in order to produce the .conf file for the vertex generator.
[source_calib_act_b.csv](https://github.com/SuperNEMO-DBD/Falaise/files/7121260/source_calib_act_b.csv)

And a picture based on this file.
![bi207_source2](https://user-images.githubusercontent.com/20680400/132369186-4d1bf2ca-59d1-4aa5-b327-48f9271274ae.png)

**Comment by lemiere** [comment] 2021-09-07 15:23
![Capture d’écran_2021-09-07_17-22-38](https://user-images.githubusercontent.com/20680400/132370565-99003a84-c99e-42a8-96fd-32c6ae1e61e8.png)

script to produce .def file ready.
Need to add stuff for variant system.
Is there someone to integrate it into Falaise ?

**Comment by fmauger** [comment] 2021-09-08 20:14
can you send your script ?

**Comment by lemiere** [comment] 2021-09-08 20:35
That's dirty but done during lunch time :-D
Best,
Yves

**Comment by fmauger** [comment] 2021-09-20 10:45
A first implementation of the realistic SDS calibration setup is available at:
https://github.com/fmauger/Falaise/tree/feature-237/

It includes:
- bump of the geometry version from 4.0 to 5..0
- need Bayeux 3.5 for ranking and/or obfuscated variant options when loooooong lists of options is available
  * now use ranking for vertex generators variant selection
  * now use ranking for primaries variant selection 
- compatibility with the legacy approximated Bi207 calib source system with all deployed 42 sources, and uniform vertex generation (no activity-based weighting)
- geometry variant enabling the individual selection of Bi207 calibration tracks (from 0 to 5) with each track enabling its 7 sources
- vertex generation variant enabling a new set of vertex generators (VG) from the SDS setup: 
  + select one unique Bi207 source
  + select one unique  Bi207 track (7 sources VG with activity based weights)
  + select all or part of  6 Bi207 tracks (activity based weighted)
- some test report at: https://github.com/fmauger/Falaise/tree/feature-237/utilities/geometry/test-issue237
- some validation test included in the standard Falaise test suite
- the variant dependency manager is able (if no bug!) to detect when the new  vertex generators (>=1 SDS track, 1 SDS source) should be available, depending on the geometry deployment (variant user choice)
- no constrains have been implemented to limit the use of the SDS source VG to the only Bi207 primaries generator (however people are supposed to use it for that purpose only because the weights have been set from the specific Bi207 measurements, from Miroslav's document and Yves' summary data file).

Below a picture of the geometry with only SDS tacks 0, 3 and 5 deployed:
![check_sds_selection_1](https://user-images.githubusercontent.com/13448163/133990197-31b24537-de1f-4f0e-9975-50919ba087ef.jpeg)

**Comment by fmauger** [comment] 2021-09-20 10:46
Are we ready for a PR on it ?

**Comment by lemiere** [comment] 2022-07-29 13:34
Based on : http://nile.hep.utexas.edu/DocDB/ut-nemo/docs/0048/004816/001/DT_FR_FINAL.pdf#cite.DEPLSYST 
(PAGE 77 Table 3.7)
Source column 1, row 1 is ID : 79 with activity 127.1 Bq.
Confirmed with @miroslav-macko, in his thesis column 1 is tunnel side.


In Falaise Column 0, Row 0 is bottom/mountain side and that's the actual calibration source label for source 79.
Taht should be fixed :-(

**Comment by fmauger** [comment] 2022-10-19 11:05
About to be fixed in some coming soon PR ;-)

**Closed as completed** 2023-09-24 21:38 UTC
